config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"

  resources :tasks do
    collection do
      get :completed
    end

    member do
      patch 'mark_complete'
    end

    resources :subtasks, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task
  validates :content, presence: true, allow_nil: false, length: { in: 5..60 }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtasks, dependent: :destroy

  # callbacks
  after_initialize :set_task_content_original
  before_save :set_priority
  after_commit :update_task_log
  # TO DO: complete all subtaks makes task complete

  # validations
  validates :content, presence: true, length: { in: 10..1500 }
  validates :importance, inclusion: { in: 1..5 }
  validate :due_date_must_be_in_future
  # validates :name, presence: true, allow_nil: true, length: { in: 5..15 }


  private

  # def subtask_limit
  #   if subtask.count > 10
  #     errors.add(:base, "Task can't have more than 10 subtasks")
  #   end
  # end

  def set_task_content_original
    # take a copy of the original task content
    self.content_original = content
  end

  def due_date_must_be_in_future
    # allow nil values, only valid if there IS a date entered
    return if due_date.nil?

    errors.add(:due_date, "can't be in the past") unless due_date >= Date.today
  end

  def set_priority
    # set priority based on due date and count of subtasks
    time_factor = due_date ? 30 / (due_date - Date.today).to_i : 1
    self.priority = (subtasks.count + 1) * importance * time_factor
  end

  def update_task_log
    subtasks = []
    File.open(Rails.public_path.join('task_log.txt'), 'w') do |file|
      Task.all.order('due_date DESC, importance').each do |record|
        subtasks << record.subtasks.each(&:content)
        # file.write("#{record.name}, #{record.reason}, by #{record.due_date}\n#{subtasks.join('\n-') if subtasks.any?}")
        file.write("#{record.name}, #{record.reason}, by #{record.due_date}\n")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/subtasks_controller.rb
  class SubtasksController < ApplicationController
    before_action :set_task, only: %i[create update destroy]

    def create
      @subtask = Subtask.new(subtask_params)
      @subtask.task = @task

      if @subtask.save
        redirect_to request.referer
      else
        flash[:error] = "Subtask #{@subtask.errors[:content].last}" unless @subtask.save
        redirect_to :root
      end
    end

    def update
      @task = Task.find(params[:task_id])
      @subtask = @task.subtasks.find(params[:id])
      @subtask.completion = params[:subtask][:completion] == '1'
      if @subtask.save
        redirect_to request.referer, status: :see_other
      else
        # this needs to be a modal
        render json: { success: false, errors: @subtask.errors.full_messages }
      end
    end

    def destroy
      @subtask = Subtask.find(params[:id])
      if @subtask.destroy
        redirect_to request.referer, status: :see_other
      else
        # this needs to be a modal
        render json: { success: false, errors: @subtask.errors.full_messages }
      end
    end

    private

    def subtask_params
      params.require(:subtask).permit(:content, :completion)
    end

    def set_task
      @task = Task.find(params[:task_id])
    end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @new_task = Task.new
    @new_tasks = Task.where.not(content: nil).where(reason: [nil, '']).order(created_at: :desc)
                     .or(Task.where.not(content: nil).where(due_date: [nil, ''])).order(created_at: :desc)
                     .or(Task.where.not(content: nil).where(name: [nil, ''])).order(created_at: :desc)
    @tasks = Task.where.not(name: ['', nil], due_date: ['', nil], reason: ['', nil])
                 .where(completion: false).order(priority: :desc)
    @subtask = Subtask.new
  end

  def completed
    @tasks = Task.where(completion: true)
  end

  def create
    @task = Task.new(task_params)
    flash[:error] = "Note #{@task.errors[:content].last}" unless @task.save
    redirect_to root_path
  end

  def edit
    # TO DO: Create modal, note view
    @task = Task.find(params[:id])
    @subtask = Subtask.new
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params.except("source_path"))
      redirect_to root_path
    else
      unless params[:task]["source_path"] == "/"
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def mark_complete
    @task = Task.find(params[:id])
    redirect_to root_path if @task.update(completion: true)
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def task_params
    params.require(:task).permit(:content, :name, :reason, :due_date, :importance, :completion, :source_path)
  end

  def subtask_params
    params.require(:task).permit(:content, :completion)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calculate_time_difference(start_time, end_time)
    difference_in_seconds = (end_time - start_time).to_i
    days = difference_in_seconds / (24 * 60 * 60)
    remaining_seconds = difference_in_seconds % (24 * 60 * 60)
    hours = remaining_seconds / (60 * 60)
    minutes = (remaining_seconds % (60 * 60)) / 60

    { days:, hours:, minutes: }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCleartasks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%# Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">

     <%# Fontawesome %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-wvfXpEpFIMBd2NZKK89AIKRMFl6Ro8SHr/JcK8jp4lLjlwQ2ORn0Z5k7bS5Fa4gB" crossorigin="anonymous">

    <%# Turbo %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if action_name == 'index' %>
      <div class="container-main">
        <%= yield %>
      </div>
      <% else %>
        <%= yield %>
      <% end %>

      <%= render "shared/alert" %>

    <%# Bootstrap & popperJS %>
    <%# Commented out for now, preventing accordion tabs to close %>
    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.js" integrity="sha384-5nxO28basTN0oojjESwP8Qm4oVsGeeMYOqXZTlbkw/fIOmXQcJnrDX3O6HBAmdDz" crossorigin="anonymous"></script> %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible fade show border border-1" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/tasks/_add_task_details.html.erb
<div class="update-form d-flex">
  <li class="container-note-info" id="<%= index %>"
   data-action="click->toggle-notes#toggleNoteDetails" data-toggle-notes-target="noteTitle">
    <p class="note-info note-title">
      <%= task.content.slice(0, 80) %>
    </p>
    <%# DAYS SINCE SAVED %>
    <p class="note-info note-number">
      <%= (Date.today - task.created_at.to_date).to_i %>
    </p>
    <%# # OF LINES %>
    <p class="note-info note-number">
      <%= task.content.lines.size %>
    </p>
  </li>
  <%= render "tasks/task_details_form", {task:task, index:index} %>
</div>

app/views/tasks/_new_notes.html.erb
<div class="container-notes-new">
  <%= simple_form_for new_task, html: { class: "form-new-notes bg-black m-0", autocomplete: "off",  data: { 'new-note-form-submit-target': 'form' } } do |f| %>
    <%= f.input :content,
      required: true, label: false, wrapper: false,
      input_html: { class: 'input-notes bg-black', placeholder: 'Add your notes here...' }
    %>
  <% end %>
  <p class="instruction-note bg-black">Press [Ctrl + Enter] to save notes</p>
</div>

app/views/tasks/_new_subtask.html.erb
<div class="new-subtask-container" data-controller="subtask" data-target="subtask">
  <%# <% unless @subtask.nil? %>
    <%= form_for [task, @subtask], url: task_subtasks_path(task), html: { data: { 'subtask-target': 'form' }, class: "m-0" } do |f| %>
      <%# this needs setting up properly with JS/Ajax %>
      <% if task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(task.errors.count, "error") %> stopped this task from being saved:</h2>
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="input-group input-group mt-3 mb-2">
        <%= f.text_field :content, placeholder: "Enter sub task", class: "form-control border-0 subtask-input", data: { 'subtask-target': 'content' } %>
        <%= button_tag(type: 'submit', class: "btn btn-sm btn-light btn-new-subtask m-0 pe-1 fs-1") do %>
          <i class="fa-solid fa-plus"></i>

        <% end %>
      </div>
    <% end %>
  <%# <% end %>
</div>

app/views/tasks/_notes.html.erb
<% if new_tasks.empty? %>
  <hr>
  <p class="no-notes">No notes - you're on top of things 👍</p>
  <hr>
<% else %>
  <ul class="list-notes" data-controller="toggle-notes">
    <% new_tasks.each_with_index do |task, index| %>
      <%= render "tasks/add_task_details", {task:task, index:index} %>
    <% end %>
  </ul>
<% end %>

app/views/tasks/_show_subtasks.html.erb
<div class="subtask-container">
  <% task.subtasks.each do |st| %>
    <div class="sub-task-item mb-1">
      <p class="new-subtask-text"><%= st.content %></p>
      <div class="flex-grow-1"></div>
      <%= link_to task_subtask_path(task, st), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "me-2" do %>
        <i class="fa-solid fa-square-xmark text-danger fs-4"></i>
      <% end %>
    </div>
<% end %>
</div>

app/views/tasks/_task_details_form.html.erb
<div class="update-task hidden" data-toggle-notes-target="noteDetails">
  <%= simple_form_for task, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, defaults: { input_html: { class: "note-details" }, label: false } do |f| %>
    <%# Hidden field for dynamic page rendering for errors %>
    <%= f.hidden_field :source_path, value: request.fullpath %>

    <div class="row mb-0">
      <div class="col-md-6">
        <%= f.input :name, required: true,  placeholder: "Task name: I have to...", grid_wrapper_html: { class: "flex-grow-1" } %>
      </div>
      <div class="col-md-3">
        <%= f.input :reason, required: true,  placeholder: 'Because/in time for...', grid_wrapper_html: { class: "flex-grow-1" } %>
      </div>
      <div class="col-md-3">
        <%= f.input :due_date, html5: true, min: Date.today.to_s, input_html: { class: 'note-details' } %>
      </div>
    </div>
    <div class="row my-2">
      <div class="col-md-6">
        <div data-controller="importance">
          <label class="integer optional form-label text-light mt-1 mb-0 p-0" for="task_importance">
            Importance: <span data-importance-target="span">1</span>
          </label>
          <%= f.input :importance, as: :range, input_html: { data: { action: "input->importance#changeImportance", "importance-target": "slider" }, min: '1', max: '5' } %>
          <%= f.input :content, input_html: { rows: 5 }, grid_wrapper_html: { class: "flex-grow-1 mb-2" } %>
        </div>
        <div class="w-100">
          <%# buttons %>
          <div class="d-flex flex-row-reverse">

            <%# Save %>
            <%= button_tag(type: 'submit', class: "btn btn-sm btn-light me-2") do %>
              <i class="fa-solid fa-floppy-disk"></i>
            <% end %>
            <%# TO DO: summary modal %>

            <%# Delete note %>
            <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger me-2" do %>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>

            <%# Close %>
            <button class="w-100 me-2 btn btn-sm btn-light" id ="<%= index %>"
              data-toggle-notes-target="closeNoteBtn" data-action="click->toggle-notes#toggleNoteDetails">
              <i class="fa-solid fa-chevron-up"></i>
            </button>
          </div>
        </div>
      </div>
  <% end %>
      <div class="col-md-6">
        <%= render "new_subtask", {task:task} %>
        <%= render "show_subtasks", {task:task} %>
      </div>
    </div>
  <%# End is on line 43 to prevent form nesting %>
</div>

app/views/tasks/_tasks.html.erb
<% if @tasks.empty? %>
  <hr>
  <p class="text-center">No tasks - you're on top of things</p>
  <hr>
<% else %>
  <div class="accordion bg-transparent" id="accordionTasks">
  <%# raise %>
    <% @tasks.each_with_index do |task, index| %>
      <div class="accordion-item border-0">
        <h2 class="accordion-header mb-0" id="heading<%= index %>">
          <button
            <%# bootstrap %>
            class="accordion-button task-name" type="button"
            data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="false" aria-controls="collapse<%= index %>"
            <%# Stimulus %>
            data-action="click->hide-task-tabs#highlightCurrentTask"
            data-hide-task-tabs-target="taskTabButton"
            >
            <h3 class="task-name-text">
              <%= task.name %>:
              <%= task.priority %>
            </h3>
          </button>
        </h2>
        <div id="collapse<%= index %>" class="accordion-collapse collapse border-bottom" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionTasks">
          <div class="accordion-body task-body text-light">
            <div class="task-body-content">
              <p>You have to <strong><%= task.name %></strong></p>
              <% if task.due_date.present? %>
                <p>By <strong><%= task.due_date.strftime('%A %e %B') %></strong></p>
              <% end %>
              <p><%= task.reason %></p>
              <div class="d-flex flex-column"
                data-controller="mark-subtask-complete"
              >
                <% task.subtasks.each_with_index do |st, index| %>
                  <div class="div-subtask d-flex flex-row bg-gray">
                    <%= form_for [task, st], method: :put, data: {'mark-subtask-complete-target': 'subtaskCheckboxForm'} do |form|  %>
                      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                      <p class="subtask-text <%= st.completion ? 'strikethrough' : '' %>"
                        data-mark-subtask-complete-target="subtaskText">
                        <%= st.content.truncate(35) %>
                      </p>
                      <div class="flex-grow-1"></div>
                      <%= form.check_box :completion, data: { 'mark-subtask-complete-target': 'checker' }, style: 'display: none;', checked: st.completion %>
                        <div class="subtaskCheckIconDiv" id="<%= index %>"
                          data-mark-subtask-complete-target="iconSubtaskCompletion"
                          data-action="click->mark-subtask-complete#toggleCompletion"
                        >
                          <% if st.completion %>
                            <i class="fa-solid fa-square subtask-checker"></i>
                          <% else %>
                            <i class="fa-regular fa fa-square subtask-checker"></i>
                          <% end %>
                        </div>
                    <% end %>
                  </div>
                <% end %>
                <%# mark all complete button %>
                <% if task.subtasks.any? { |subtask| !subtask.completion } %>
                  <div class="subtasks-all-complete-button"
                    data-action="click->mark-subtask-complete#toggleCompletionAll"
                  >
                    <p class="fw-bold text-center" style=" width: fit-content;">
                      Toggle all
                    </p>
                    <input id="check-all-<%= index %>"
                      style="display:none;"
                      type="checkbox"
                      data-mark-subtask-complete-target="checkAllIcon"
                    >
                    <div class="subtaskCheckIconDiv">
                      <i
                        class="fa-regular fa-square-check all-subtasks-checker"
                        data-mark-subtask-complete-target="completedAll"
                      ></i>
                      </div>
                  </div>
                <% end %>

              </div>
              <hr>
              <%# buttons to edit, view original note and add subtasks %>
              <div class="task-buttons">
                <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Deleting detailed task, are you sure?' }, class:" btn btn-outline-danger me-2 fw-bold" do %>
                  Delete
                <% end %>
                <%= link_to edit_task_path(task), class:"task-btn btn btn-outline-light me-2 fw-bold" do %>
                  Edit
                <% end %>
                <%= link_to mark_complete_task_path(task), data: { turbo_method: :patch, turbo_confirm: 'Complete task?' }, class: " btn btn-success  fw-bold" do %>
                  Done!
                <% end %>
              </div>
              <hr>
              <p class="see-note-button">
                 <%# MODAL SHOULD BE HERE %>
                <em>See original note</em>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tasks/completed.html.erb
<div class="container m-4">
  <div class="d-flex justify-content-between">
    <h2>
      <%= link_to :root, class: "text-decoration-none" do %>
        <i class="fa-solid fa-circle-left"></i>
      <% end %>
      <strong>Completed tasks</strong>
    </h2>
  </div>
  <hr>
  <div>
    <div class="container">
      <% @tasks.each do |task| %>
        <h5>
        <%= task.name %>:
        </h5>
        <small>
          <% difference = calculate_time_difference(task.created_at, task.updated_at) %>
          Days: <%= difference[:days] %>, Hours: <%= difference[:hours] %>, Minutes: <%= difference[:minutes] %>
        </small>
        <p>
          Importance:
          <% task.importance.times do %>
            <small><i class="fa-solid fa-square"></i></small>
          <% end %>
        </p>
        <p>
          [ a dynamic icon for how long it took to complete the task]
        </p>
        <div class="container d-flex flex-row">
          <p class="me-4">
            <i class="fa-solid fa-chevron-down"></i>
            Show subtasks
          </p>
          <p>
            <i class="fa-solid fa-chevron-down"></i>
            Show task content
          </p>
        </div>

        <small>Created <%= task.created_at.to_fs(:long) %></small> |
        <small>Completed <%= task.updated_at.to_fs(:long) %></small> |
        <small>
          Priority:
          <% task.priority.to_i.times do %>
            <small><i class="fa-solid fa-fire"></i></small>
          <% end %>
        </small>
        <hr>
      <% end %>
    </div>


  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container m-4">
  <div class="d-flex justify-content-between">
    <h2>
      <%= link_to :root, class: "text-decoration-none" do %>
        <i class="fa-solid fa-circle-left"></i>
      <% end %>
      <strong>
        Edit task:
      </strong>
      <%= @task.name %>
    </h2>
  </div>
  <hr>
  <%# DISPLAY SUBTASKS %>


  <div>
    <%= render "show_subtasks", {task:@task} if @task.subtasks.present? %>
    <%= render "new_subtask", {task:@task} %>
  </div>
  <%= simple_form_for @task do |f| %>
    <%# Hidden field for dynamic page rendering for errors %>
    <%= f.hidden_field :source_path, value: request.fullpath %>

    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, required: true %>
    <hr>
    <%= f.label :content, class: 'form-label' %>
    <%= f.text_field :content, required: true %>
    <hr>
    <%= f.label :reason, class: 'form-label' %>
    <%= f.text_field :reason, required: true %>
    <hr>
    <%= f.label :due_date, class: 'form-label' %>
    <%= f.input :due_date, html5: true, min: Date.today.to_s, label: false %>
    <hr>
    <%= f.label :importance, class: 'form-label' %>
    <label class="integer optional form-label text-light mt-1 mb-0 p-0" for="task_importance">
      <span data-importance-target="span">1</span>
    </label>
    <%= f.input :importance, as: :range, input_html: { min: '1', max: '5' }, label: false %>
    <hr>
    <%= f.label :content_original, "Original note", class: 'form-label' %>
    <%= f.input :content_original, input_html: { rows: 3 }, grid_wrapper_html: { class: "flex-grow-1 mb-2" }, label: false %>
    <hr>
    <%= f.label :completion, class: 'form-label' %>
    <%= f.check_box :completion %>
    <hr>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container-tasks border-end" data-controller="hide-task-tabs">
  <h2 class="section-title m-0" data-hide-task-tabs-target="tasksTitle">
    Tasks
  </h2>

  <%# See completed tasks button %>
  <%= link_to completed_tasks_path, class: "see-completed-collapsed", aria: { label: "See completed tasks" } do %>
    <p class="text-hidden">See completed tasks</p>
    <i class="fa-solid fa-chevron-down"></i>
  <% end %>

  <%= render "tasks/tasks", tasks: @tasks %>
</div>

<%# New tasks entered as rough notes %>
<div class="container-notes-col"
  data-controller="new-note-form-submit"
>
  <%= render "tasks/new_notes", new_task: @new_task %>

  <%# Notes that need details from user %>
  <div class="container-notes-details">
    <h2 class="section-title">Notes</h2>
    <%= render "tasks/notes", new_tasks: @new_tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
Add a new note
  <%= simple_form_for(@task) do |form| %>
    <div>
      <p>CAR</p>
      <%= form.label :content %>
      <%= form.text_field :content, required: true %>
    </div>
    <%= form.submit "Create Task" %>
  <% end %>
<hr>